import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  const date = new Date();

console.log(date.toString(), "yes");
  return (
    <div className={styles.container}>
      <Head>
        <title>My Wish List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1>

     
    </div>
  )
}
